name: robodiff
channels:
  - pytorch
  - pytorch3d
  - nvidia
  - conda-forge
dependencies:
  - python=3.9
  - pip=22.2.2
  - cudatoolkit=11.6
  - pytorch=1.12.1
  - torchvision=0.13.1
  - pytorch3d=0.7.0
  - numpy=1.23.3
  - numba==0.56.4
  - scipy==1.9.1
  - py-opencv=4.6.0
  - matplotlib=3.6.1
  - zarr=2.12.0
  - numcodecs=0.10.2
  - h5py=3.7.0
  - hydra-core=1.2.0
  - einops=0.4.1
  - tqdm=4.64.1
  - dill=0.3.5.1
  - wandb=0.13.3
  - threadpoolctl=3.1.0
  - imageio=2.22.0
  - imageio-ffmpeg=0.4.7
  - termcolor=2.0.1
  - tensorboard=2.10.1
  - tensorboardx=2.5.1
  - psutil=5.9.2
  - click=8.0.4
  - accelerate=0.13.2
  - diffusers=0.11.1
  - av=10.0.0
  - llvm-openmp=14
  - imagecodecs==2022.8.8
  - pip:
    - imagecodecs==2022.9.26
